DEFAULT:
  libs: [protobuf, json-c, openssl]
  cxxflags: [-std=c++11]
  cxxflagscli: [Magick++-config --cppflags --cxxflags]
  lflagscli: [Magick++-config --libs --ldflags]
  debug:
    cflags: [-O0, -DDEBUG, -D_DEBUG]
  release:
    cflags: [-O3, -DNDEBUG]
